spring:
  application:
    name: Carservice

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}


#spring.application.name=Carservice
#
#server.port=8081
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/Carsharing
#spring.datasource.username=postgres
#spring.datasource.password=1111
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.kafka.bootstrap-servers=localhost:9092