spring.application.name=Carservice

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/Carsharing
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=localhost:9092