spring.application.name=ReservationsService

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/Carsharing
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.consumer.properties.spring.json.value.default.type=com.shared.dto.ShortCarInfoDTO
spring.kafka.consumer.properties.spring.json.trusted.packages=*